---
- name: install apache
  hosts: ec2
  user: ubuntu
  sudo: yes
  gather_facts: no
  pre_tasks: 
  - name: install python 
    raw: sudo test -e /usr/bin/python || (sudo apt update && sudo apt install -y python-minimal)
  tasks:
  - name: install nginx
    apt:
      name: apache2
      state: latest   
 
